name: Xiaozl
# avatar: images/profile.png # Avatar image. Default to "images/profile.webp".
bio: '喜欢研究有意义的东西'
# company: "" # HTML markup are supported, such as: <a href="https://example.com" target="_blank" rel="noopener noreferrer">Company</a>.
# location: "" # HTML markup are supported, such as: <a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>.
# about: https://razonyang.com # The external about page. The internal about page will be used if not set.
params: {
  # layout: compact
}
social:
  email: xiaozelan@126.com
  # github: xiaozl
  # twitter: ""
  # patreon: ""
  # paypal: ""
  # rss: "" # Remove RSS
