# en:
#   languageName: English
#   weight: 1

zh-cn:
  languageName: 简体中文
  weight: 4
  params:
    dateFormat: '2006-01-02'
    description: 一个有意义的网站
    keywords: 'AI,AI进行时'
    archive:
      dateFormat: 01-02