backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

media_folder: static/img
public_folder: /img

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: '{{slug}}'
    editor:
      preview: false
    fields:
      - { label: '标题', name: 'title', widget: 'string' }
      - { label: '发布日期', name: 'date', widget: 'datetime' }
      - { label: '描述', name: 'description', widget: 'text' }
      - { label: "特色图片", name: "featured_image", widget: "image" }
      - { label: '分类', name: 'category', widget: 'string', default: "碎碎念" }
      - { label: '内容', name: 'body', widget: 'markdown' }